[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "sxpb_example"
version = "0.0.0"
authors = [
]
dependencies = [
]
requires-python = ">=3.9"

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "sxpb @ git+https://github.com/sxproto/sxpb-py@4a2ce27ba7863a22ca298b9e32cfa54f2fe6716b",
]

[tool.pytest.ini_options]
addopts = "-v"
pythonpath = ["test"]
testpaths = ["test"]

[tool.pdm.scripts]
test = "pytest"
