name: Test Python

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install PDM
      run: pip install pdm
    - name: Install dependencies
      run: pdm install
    - name: Run tests
      run: pdm run test
